services:
  emulator:
    build: .
    container_name: camera-emulator
    restart: unless-stopped
    ports:
      - "5001:5000"
      - "554:554"
      - "1935:1935"
      - "8880:8888"
      - "8881:8889"
      - "9200-9300:9200-9300"
    volumes:
      - ./videos:/app/videos
      - ./config:/app/config
      - ./mediamtx.yml:/mediamtx.yml
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
